project_id = "lpyexykkrvljgpayxqfl"

[functions.search-sentinel1]
verify_jwt = false

[functions.get-sentinel1-data]
verify_jwt = false

[functions.analyze-risk-areas]
verify_jwt = false

[functions.get-ibge-population]
verify_jwt = false

[functions.get-nasa-worldview]
verify_jwt = false

[functions.get-ibge-socioeconomic]
verify_jwt = false

[functions.get-observearth-data]
verify_jwt = false

[functions.search-planetary-data]
verify_jwt = false

[functions.process-water-index]
verify_jwt = false

[functions.get-ibge-municipalities]
verify_jwt = false
